# Generated by Django 2.2.7 on 2019-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(upload_to='inputs/')),
                ('outputFile', models.FileField(upload_to='outputs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InputData',
        ),
        migrations.DeleteModel(
            name='OutputData',
        ),
    ]
