# Generated by Django 3.0.2 on 2020-01-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airun', '0002_auto_20191222_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='id',
            field=models.TextField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
