# Generated by Django 3.0.2 on 2020-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airun', '0003_auto_20200112_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
