# Generated by Django 3.0.2 on 2020-01-25 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airun', '0004_auto_20200112_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='epoch',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
