# Generated by Django 3.0.2 on 2020-02-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airun', '0005_teacherdata_epoch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherData',
        ),
    ]
